# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'priority:critical'
color: 'd73a4a'
description: 'Must be fixed immediately. Blocks releases.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'priority:high'
color: 'ff6f59'
description: 'Should be worked on soon; blocks major features.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'priority:medium'
color: 'fbca04'
description: 'Normal importance tasks.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'priority:low'
color: 'c2e0c6'
description: 'Nice-to-have, no urgency.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'type:feature'
color: '0e8a16'
description: 'New functionality for automation tools.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'type:enhancement'
color: '84b6eb'
description: 'Improvements to existing workflows.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'type:bug'
color: 'd73a4a'
description: 'Incorrect or failing behavior.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'type:refactor'
color: 'c5def5'
description: 'Internal code-level improvement.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'type:documentation'
color: '006b75'
description: 'Documentation or README updates.'

---
# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/label.schema.yml
name: 'type:chore'
color: 'ededed'
description: 'Maintenance, CI updates, or dependency updates.'
