# yaml-language-server: $schema=../node_modules/@aliaksandarpratashchyk/kickcat/schemas/milestone.schema.yml
# hash: de5ec9f5f7bf2207f6165252a96ea213

number: 3
title: 🚀 Project Setup & Initial Implementation
state: closed
description: |
  Initialize the repository structure and developer tooling for the Suspenders TypeScript library.
  Scaffold the first usable API surface (assertions, safe casts, and common type guards).

  ### 🎯 Goal
  Establish a clean, reproducible foundation for building, testing, documenting, and publishing the library.

  ### ✅ Outcomes
  - TypeScript project scaffolded (strict config, declarations)
  - Build pipeline in place (webpack bundle + `.d.ts`)
  - API docs generation wired up (API Extractor + API Documenter)
  - Test + coverage reporting configured (Jest + coverage badge artifacts)
  - Initial core implementation shipped (`assert`, `safe`, `unsafe`, `is*` type guards)
